[workspace]
resolver = "2"
members = [
    "crates/qst-core",
    "crates/qst-ecs",
    "crates/qst-input",
    "crates/qst-asset",
    "crates/qst-scene",
    "crates/qst-physics",
    "crates/qst-render",
    "crates/qst-audio",
    "crates/qst-editor",
    "crates/qst-engine",
    "playground",
]

[workspace.package]
edition = "2024"
version = "0.0.2"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/Qustellar/Quasar"

[workspace.dependencies]
bevy_ecs = "0.19.1"
bytemuck = { version = "1", features = ["derive"] }
egui = "0.33"
egui-wgpu = "0.33"
egui-winit = "0.33"
gltf = "1.4"
glam = { version = "0.30", features = ["serde"] }
blake3 = "1"
notify = "8"
rapier3d = "0.35"
ron = "0.10"
bincode = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
wgpu = "27"
winit = "0.30"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
rodio = { version = "0.21", default-features = false, features = ["wav", "mp3", "vorbis", "playback"] }
