[package]
name = "qst-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
qst-core = { path = "../qst-core" }
rodio = { workspace = true, optional = true }

[features]
default = ["rodio-backend"]
rodio-backend = ["dep:rodio"]
