[package]
name = "qst-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
qst-core = { path = "../qst-core" }
qst-scene = { path = "../qst-scene" }
wgpu.workspace = true
winit.workspace = true
